import { startRegistration, startAuthentication } from '@simplewebauthn/browser';
import { auth } from '../firebase';
import { signInWithCustomToken } from 'firebase/auth';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'https://manaintibojanam-backend.onrender.com';
const API_BASE = `${API_BASE_URL}/api/auth`;

/**
 * Checks if the device supports WebAuthn/Passkeys and has a platform authenticator (Face ID/Fingerprint)
 */
export async function isBiometricSupported(): Promise<boolean> {
  // WebAuthn is supported
  if (!window.PublicKeyCredential) {
    return false;
  }
  
  // Check if a platform authenticator is available (FaceID, TouchID, Windows Hello)
  try {
    const isAvailable = await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
    return isAvailable;
  } catch (e) {
    return false;
  }
}

/**
 * Register a new Passkey for the currently logged-in user
 */
export async function registerBiometric(userId: string, email?: string | null, displayName?: string | null): Promise<boolean> {
  try {
    // 1. Get registration options from server
    const resp = await fetch(`${API_BASE}/generate-registration-options`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId, email, displayName }),
    });

    if (!resp.ok) {
      throw new Error('Failed to fetch registration options');
    }

    const options = await resp.json();

    // 2. Prompt user to create a passkey (Face ID / Fingerprint prompt appears)
    let attResp;
    try {
      attResp = await startRegistration(options);
    } catch (error: any) {
      if (error.name === 'InvalidStateError') {
        throw new Error('Authenticator was probably already registered by user');
      }
      throw error;
    }

    // 3. Send response back to server for verification
    const verificationResp = await fetch(`${API_BASE}/verify-registration`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId,
        response: attResp,
      }),
    });

    const verificationResult = await verificationResp.json();
    
    if (verificationResult.verified) {
      // Mark locally that the user has set up biometrics
      localStorage.setItem('has_biometrics_enabled', 'true');
      return true;
    }

    return false;
  } catch (error) {
    console.error('Biometric registration failed:', error);
    throw error;
  }
}

/**
 * Authenticate using an existing Passkey (Face ID / Fingerprint)
 */
export async function loginWithBiometric(): Promise<boolean> {
  try {
    // 1. Get auth options from server
    const resp = await fetch(`${API_BASE}/generate-authentication-options`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    });

    if (!resp.ok) {
      throw new Error('Failed to fetch authentication options');
    }

    const { options, challengeId } = await resp.json();

    // 2. Prompt user to authenticate (Face ID / Fingerprint prompt appears)
    const asseResp = await startAuthentication(options);

    // 3. Send response to backend to verify and get Firebase Custom Token
    const verificationResp = await fetch(`${API_BASE}/verify-authentication`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        challengeId,
        response: asseResp,
      }),
    });

    const verificationResult = await verificationResp.json();

    if (verificationResult.verified && verificationResult.token) {
      // 4. Log in to Firebase using the Custom Token generated by the backend
      await signInWithCustomToken(auth, verificationResult.token);
      return true;
    }

    return false;
  } catch (error) {
    console.error('Biometric authentication failed:', error);
    throw error;
  }
}

export function hasBiometricsEnabledLocally(): boolean {
  return localStorage.getItem('has_biometrics_enabled') === 'true';
}
