apiVersion: v1
kind: Service
metadata:
  name: menu-projection-worker
spec:
  selector:
    app.kubernetes.io/name: menu-projection-worker
  ports:
    - { port: 8080, name: http }
    - { port: 9090, name: metrics }
