replicaCount: 2
image:
  repository: bhojanos-api
  tag: staging-latest
serviceAccount:
  name: staging-api-sa
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: staging-api.bhojanos.internal
      paths:
        - path: /
          pathType: Prefix
resources:
  requests: { cpu: 250m, memory: 256Mi }
  limits: { cpu: 500m, memory: 512Mi }
