/** Stable reason codes for AI canary live rollout gates (Phase 25). */

export const AI_CANARY_PROMOTION_BLOCKERS = {
  GATES_DISABLED: 'AI_CANARY_LIVE_ROLLOUT_GATES_DISABLED',
  FLAG_DISABLED: 'AI_CANARY_ROLLOUT_FLAG_DISABLED',
  NOT_WIRED: 'AI_CANARY_NOT_WIRED_INTO_ASSIST',
  MANUAL_APPROVAL_REQUIRED: 'MANUAL_APPROVAL_REQUIRED',
  STAGE_AT_MAX: 'STAGE_AT_MAXIMUM',
  HEALTH_FAILING: 'LIVE_HEALTH_GATE_FAILING',
  ROLLBACK_REQUIRED: 'ROLLBACK_REQUIRED',
  HALT_ACTIVE: 'HALT_RECOMMENDED',
  GOLDEN_FAILED: 'GOLDEN_EVAL_PRECHECK_FAILED',
  GOLDEN_UNKNOWN: 'GOLDEN_EVAL_PRECHECK_UNKNOWN',
  SHADOW_FAILED: 'SHADOW_COMPARE_PRECHECK_FAILED',
  SHADOW_INSUFFICIENT: 'SHADOW_SAMPLES_INSUFFICIENT',
  GATEWAY_NOT_READY: 'AI_GATEWAY_NOT_READY',
  SOAK_INCOMPLETE: 'MIN_SOAK_NOT_MET',
} as const;

export const AI_CANARY_HALT_TRIGGERS = {
  HEALTH_GATE: 'LIVE_HEALTH_GATE',
  SAFETY_SPIKE: 'SAFETY_BLOCKED_RATE_SPIKE',
  FAILURE_SPIKE: 'FAILURE_RATE_SPIKE',
  LATENCY_SPIKE: 'P95_LATENCY_SPIKE',
  CANARY_ERROR_SPIKE: 'AI_CANARY_ERROR_CODE_SPIKE',
  NONE: 'NONE',
} as const;

export const AI_CANARY_ROLLBACK_TRIGGERS = {
  HEALTH_BREACH: 'ROLLBACK_HEALTH_BREACH',
  SAFETY_BREACH: 'ROLLBACK_SAFETY_BREACH',
  LATENCY_BREACH: 'ROLLBACK_LATENCY_BREACH',
  SHADOW_DRIFT: 'ROLLBACK_SHADOW_DRIFT',
  NONE: 'NONE',
} as const;
