route:
  group_by: [alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: staging-slack
  routes:
    - match:
        severity: critical
      receiver: staging-pagerduty
receivers:
  - name: staging-slack
    slack_configs:
      - channel: "#bhojanos-staging-alerts"
        send_resolved: true
  - name: staging-pagerduty
    pagerduty_configs:
      - service_key_file: /etc/alertmanager/pagerduty-key
