apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bhojanos-staging-spine

resources:
  - ../base/namespace.yaml
  - ../base/network-policies.yaml
  - ../base/rbac.yaml

commonLabels:
  environment: staging
  managed-by: kustomize
